// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWUdnv6w0aLoDlTlaQR-qKjhhaCzs33_Y',
    appId: '1:416204323587:web:8122abf3d5e3aa6427c736',
    messagingSenderId: '416204323587',
    projectId: 'taskmate-b809b',
    authDomain: 'taskmate-b809b.firebaseapp.com',
    storageBucket: 'taskmate-b809b.appspot.com',
    measurementId: 'G-WLYMV8YWD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJpuW8r5RtGX4w0Z1ecEXfxxUeycD5FIQ',
    appId: '1:416204323587:android:6d476e5ba403bd6d27c736',
    messagingSenderId: '416204323587',
    projectId: 'taskmate-b809b',
    storageBucket: 'taskmate-b809b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZv34e5MOnGeQhXoe6UwXC5rH2FbB1-KU',
    appId: '1:416204323587:ios:78cf0233a6f1a10427c736',
    messagingSenderId: '416204323587',
    projectId: 'taskmate-b809b',
    storageBucket: 'taskmate-b809b.appspot.com',
    iosClientId:
        '416204323587-gmlllp18i8j8dg49s6jutkflanqbjee2.apps.googleusercontent.com',
    iosBundleId: 'com.example.deadlineTracker',
  );
}
